globals:
  mode: development # development or production
  email: webmaster@banner.wtf
selfsign:
  enabled: true
  country: GB
  state: Essex
  dis: DIS
  city: Braintree
  common: test
certbot:
  enabled: false
  redirect: true # Optional
  mode: list # list or scrape
  domains:
    - leanneparkinmakeup.co.uk
    - mattbanner.co.uk
    - www.mattbanner.co.uk
    - mattbanner.dev
    - www.mattbanner.dev