globals:
  email: you@domain.com
selfsign:
  enabled: true
  country: GB
  state: Essex
  city: Chelmsford
  common: domain.com
certbot:
  enabled: false
  redirect: true
  mode: list
  domains:
    - domain.com
    - www.domain.com
    - one.domain.com
    - two.domain.com